# Generated by Django 3.1.4 on 2021-01-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('quantity', models.EmailField(max_length=100)),
                ('todayprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='itemlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('quantity', models.EmailField(max_length=100)),
                ('unitprice', models.CharField(max_length=100)),
                ('dateitem', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPurchaged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchageitem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPurchage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchageid', models.CharField(max_length=100)),
                ('purchagedate', models.CharField(max_length=100)),
                ('itempurchage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kumarBuilding.itempurchaged')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('quantity', models.EmailField(max_length=100)),
                ('unitprice', models.CharField(max_length=100)),
                ('totalprice', models.CharField(max_length=100)),
                ('customername', models.CharField(max_length=100)),
                ('customeremail', models.CharField(max_length=100)),
                ('customermobile', models.CharField(max_length=100)),
                ('customerid', models.CharField(max_length=100)),
                ('customerpurchage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kumarBuilding.customerpurchage')),
            ],
        ),
    ]
