# Generated by Django 3.1.4 on 2021-01-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlist',
            name='itemname',
        ),
        migrations.RemoveField(
            model_name='customerlist',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='customerlist',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='customerlist',
            name='unitprice',
        ),
    ]
