# Generated by Django 3.1.4 on 2021-01-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0002_auto_20210125_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlist',
            name='advance',
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerlist',
            name='borrow',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpurchage',
            name='advancet',
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpurchage',
            name='borrowt',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
