# Generated by Django 3.1.4 on 2021-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0003_auto_20210126_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchage',
            name='received',
            field=models.CharField(default=500, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpurchage',
            name='totalprice',
            field=models.CharField(default=600, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempurchaged',
            name='quantity',
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempurchaged',
            name='unitprice',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
