# Generated by Django 3.1.4 on 2021-01-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0004_auto_20210126_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlist',
            name='customeraddress',
            field=models.CharField(default='Ramkola', max_length=100),
            preserve_default=False,
        ),
    ]
