# Generated by Django 3.1.4 on 2021-01-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0005_customerlist_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='customermobile',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
