# Generated by Django 3.1.4 on 2021-01-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0006_auto_20210126_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlist',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerlist',
            name='customermobile',
            field=models.CharField(max_length=100),
        ),
    ]
