# Generated by Django 3.1.4 on 2021-01-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumarBuilding', '0007_auto_20210126_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlist',
            name='customerpurchage',
        ),
        migrations.RemoveField(
            model_name='customerpurchage',
            name='itempurchage',
        ),
        migrations.AddField(
            model_name='customerpurchage',
            name='customerlist',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='kumarBuilding.customerlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempurchaged',
            name='customerpurchage',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='kumarBuilding.customerpurchage'),
            preserve_default=False,
        ),
    ]
